### ISSUE TITLE
Seeds: use generators rather than lists

### ISSUE THREAD

**Issue by wetneb** [scrapinghub/frontera#153]
It seems that the seed loaders assume that they can load all seed URLs in memory (as a list):
https://github.com/scrapinghub/frontera/blob/master/frontera/contrib/scrapy/middlewares/seeds/__init__.py#L17
https://github.com/scrapinghub/frontera/blob/master/frontera/core/manager.py#L374

I am writing a custom seed manager that returns millions of seed URLs. So I would like frontera not to load all seeds immediately, but iterate from them to refill the crawl frontier when needed. Would it be possible to do that in Scrapy.
Obviously I would need to fix the two functions linked above so that they use generators, but would that be enough?

**Comment by sibiryakov** [comment]
Hi @wetneb. In general, I like the idea to make frontera consume batches of seeds, not loading the whole list in the memory. So, that would be nice if you could contribute this feature. Unfortunately, to implement it in full, it requires modification of all backends to accept generators instead of iterables. 

Are you talking about single process run mode? If you run a distributed setup, it could make sense to run feed the crawler with seeds by using external process generating ``add_seeds`` events in the spider log.

**Comment by wetneb** [comment]
@sibiryakov thanks for being so quick to reply!
What backends should I need to modify exactly? (Sorry I'm not entirely familiar with frontera's terminology yet.)

I am trying to run frontera in a distributed setup indeed. If I add the seeds manually using `add_seeds`, isn't there a risk that the frontier over/underflows if I am not adding them at the right rate?

**Comment by sibiryakov** [comment]
Let's start with the backend you're going to use.

https://github.com/scrapinghub/frontera/blob/master/frontera/contrib/scrapy/middlewares/seeds/__init__.py#L17 Scrapy should handle it well, but this middleware needs to be modified to bufferize reading from file.

In case of ZeroMQ - yes, in case of Kafka - this should be fine, but depends on your Kafka configuration.

**Comment by sibiryakov** [comment]
@wetneb is it answers your question? can I close it?

**Comment by wetneb** [comment]
Yes thank you, I went for a separate worker that uses the frontier API
to fill the frontier manually.

**Comment by sibiryakov** [comment]
@wetneb that's a good decision too.
