### ISSUE TITLE
Multiple ZeroMQ Brokers

### ISSUE THREAD

**Issue by LabhanshAgrawal** [scrapinghub/frontera#171]
I have setup a crawler based on the production broad crawl tutorial (Using ZeroMQ and HBase). I have tested running 2 spiders on 2 computers and they are working. They share the load and all. But I think that if I increase the number of computers or spiders then the message broker will become a bottleneck.
How can I run multiple brokers and how will be they setup i.e. settings to change, recommended number of spiders per broker, and anything else I should know.
Or if I should use Kafka instead?(then Please tell me the above things for it as well)

Thank You

**Comment by sibiryakov** [comment]
Hi @LabhanshAgrawal ZeroMQ broker is very lightweight process, and I think it could handle say 8 spiders, may be more. I would expect that bottleneck will be happening in SW and DBW much earlier. At the moment ZeroMQ broker doesn't support running multiple DBW or SW instances, so the Kafka is the way to go.

Unfortunately, there are no exact recommendations for Kafka. But I would recommend to tune it for throughput, instead of storage. E.g. run it on SSD or RAM disk and reduce the retention process overhead, and avoid hot spotting of single Kafka broker.
