### ISSUE TITLE
Windows support for Frontera

### ISSUE THREAD

**Issue by 11rohans** [scrapinghub/frontera#282]
Hi, I'm trying to use the distributed mode of Frontera for a broad crawl but I am running into issues testing it on my local machine in windows.  I am getting an import error (cannot import error name SIGUSR1) when I start a db worker due to SIGUSR1 not being available on windows. Would love if Frontera could develop a way that this software could be used on a windows machine and circumvent this issue.

**Comment by sibiryakov** [comment]
Yes, Frontera wasn't tested/developed on Windows yet, but it could be. If you can, please submit a PR fixing this.

**Comment by liho00** [comment]
Hello, is frontera version==0.8.1 support windows 10 platform now? What is the best platform to use the frontera?

**Comment by sibiryakov** [comment]
Linux!

**Comment by liho00** [comment]
![image](https://user-images.githubusercontent.com/34411102/56044385-9f7d7e00-5d71-11e9-8f74-e32898daa1ed.png)

I am a student who trying to build a distributed crawler, and i have no experience of linux, but i willing to learn it. 

Besides, im a windows user for a long time. May i wish to get your suggestion which linux distros that is suits for Frontera and easy to use.

**Comment by sibiryakov** [comment]
Ubuntu is usually a default choice in such cases.

**Comment by Prometheus3375** [comment]
If you want to use Frontera on Windows, follow next steps.

1. Install [Visual Studio Installer](https://visualstudio.microsoft.com/thank-you-downloading-visual-studio/?sku=Community&rel=16).
2. Go to `Control Panel\Programs and Features\Uninstall a program` and
remove Windows SDK AddOn if any.
3. Use VS Installer to install the latest VS C++ x64/x86 build tools and Windows SDK (<MSVC v142 - VS 2019 C++ x64/x86 build tools (v14.26)> and <Windows 10 SDK (10.0.19041.0)> for now).
4. (Optional) Initialize virtual environment and activate it according to the [tutorial](https://docs.python.org/3/library/venv.html).
5. [Update pip](https://pip.pypa.io/en/stable/installing/#upgrading-pip).
6. Run `pip install --upgrade setuptools wheel`. This will update setuptools and wheel packages.
4. Clone [python binding for CityHash](https://github.com/xcoco/python-cityhash-windows) for Windows.
5. Open `setup.py` and change version to the latest ( `0.2.3.post9` now).
6. Open PowerShell and activate virtual environment if any.
7. Change current working directory to the root of that repository.
8. Run `python setup.py install`. This will install CityHash.
9. Now you can install Frontera.
9. After installation, open sources of frontera.
10. Open `frontera/worker/db.py` and comment `signal` package import and usage (lines 8 and 129 in v0.8.1).
11. Open `frontera/worker/strategy.py` and comment `signal` package import and usage (lines 10 and 256 in v0.8.1).

Points 1-3 resolves issues with installing Twisted package and then will be also used to build CityHash.

Points 7-11 installs python binding of CityHash for Windows. CityHash from pip does not compile on Windows (#367), and thus it cannot be installed through pip. Another way is to replace CityHash usage with some other library in `frontera/contrib/backends/partitioners.py`.

Points 13-15 resolves issues occurring due to usage of Unix-specific signal. They are used for debugging: a user can sent user-defined signal SIGUSR1 to print current stack trace. This signal cannot be used on Windows.
